- src/app/layout.tsx
- src/app/modaltest/page.tsx
- src/components/modal/modalContainer/ModalContainer.tsx
- src/components/modal/modalContent/ChangeCEOInfoModal.tsx
- src/components/modal/modalContent/ChangeMyInfoModal.tsx
- src/components/modal/modalContent/ClosedAlbaformModal.tsx
- src/components/modal/modalContent/DeleteAlbaformModal.tsx
- src/components/modal/modalContent/GetMyApplicationModal.tsx
- src/components/modal/modalContent/PatchAlbaformModal.tsx
- src/components/modal/modalContent/SelectProgressModal.tsx
- src/components/modal/modalManager/ModalManager.tsx
- src/schema/modal/changeCEOInfoSchema.ts
- src/styles/globals.css
- src/types/modal.ts
1. "사장님 정보 관리" 모달 UI 구현
2. 폼 벨류데이션
3. 모달이 길어져서 스크롤로 봐야함 (글로벌에 스크롤 감추는 css 추가함)
1. 제출 기능 구현
2. 공통 버튼 사용 (모든 모달 한번에 적용하겠습니다)
3. 가게 위치 카카오맵과 연동 필요
모달의 실제 크기가 피그마에서 보여지는 크기보다 큽니다.
> Feat:"사장님 정보 관리" 모달 UI 구현

- src/atoms/dropdownAtomStore.ts
- src/components/dropdown/MyInfoEditDropdown.tsx
- 내 정보 수정, 비밀번호 변경 드롭다운을 구현했습니다.
- 다음 코드와 같이 사용이 가능합니다.
```
const handleMyInfoEdit = () => {
// 수정 로직
}
const handlePasswordEdit = () => {
// 비밀번호 변경 로직 또는 모달 연결
}
return <MyInfoEditDropdown onMyInfoEdit={handleMyInfoEdit} onPasswordEdit={handlePasswordEdit} />
```
- 알바토크 게시글 정렬 드롭다운
- 알바폼 생성 드롭다운
- 불필요한 atom 상태를 삭제했습니다.
- atom 삭제로 수정 및 삭제 드롭다운에도 반영하여 수정했습니다.
- 수정 및 삭제 드롭다운의 반응형 위치가 잘못되어 수정했습니다.
> Feat: 정보 수정 드롭다운 추가

- src/components/button/SolidButton.tsx
- src/components/modal/modalContent/ChangeCEOInfoModal.tsx
- src/components/modal/modalContent/ChangeMyInfoModal.tsx
- src/components/modal/modalContent/ChangePasswordModal.tsx
- src/components/modal/modalContent/ClosedAlbaformModal.tsx
- src/components/modal/modalContent/DeleteAlbaformModal.tsx
- src/components/modal/modalContent/GetMyApplicationModal.tsx
- src/components/modal/modalContent/PatchAlbaformModal.tsx
- src/components/modal/modalContent/SelectProgressModal.tsx
- src/schema/modal/changeCEOInfoSchema.ts
- src/schema/modal/changePasswordSchema.ts
- src/schema/modal/getMyApplicationSchema.ts
1. 8개 모달 컨탠츠에 공통 버튼 컴포넌트를 사용했습니다.
2. 모달 제목 시멘틱 태그 변경했습니다 : strong -> h2
3. 비밀번호 zod 스키마 변경했습니다 (12자 제한, 에러 문구 수정)
모달 사용법
1. useModal 임포트
2. openModal 구조분해하여 원하는 타입 인자로 받아 사용
```
const { openModal } = useMoadl();
<button onClick=(() => openModal('원하는 타입'))> 
```
제출 폼 기능 구현 필요
> Refactor:모달 내 공통 버튼 사용

- public/icon/albaform-dropdown-off.svg
- public/icon/albaform-dropdown-on.svg
- src/atoms/dropdownAtomStore.ts
- src/components/dropdown/AlbaformCreateDropdown.tsx
- 알바폼 생성 시 태블릿, 모바일화면에서 사이드바 대신 동작할 단계별 드롭다운을 구현했습니다.
- 사용은 다음 예시코드처럼 하실 수 있습니다.
- 아래 예시는 클라이언트 컴포넌트에서의 예시이고, 서버컴포넌트에서 아래와 같은 구조를 사용하신다면 atom 대신 url에 각 단계에 해당하는 값(ex. stepOne)을 단계별 클라이언트 컴포넌트에서 searchParams로 전달해주시는 방식으로 이용하실 수 있습니다. (회원가입 참조)
```
const step = useAtomValue(albaformCreateStepAtom);
console.log(step.value);
return (
<>
<AlbaformCreateDropdown />
{step.value === "stepOne" && <StepOneComponent />}
{step.value === "stepTwo" && <StepTwoComponent />}
{step.value === "stepThree" && <StepThreeComponent />}
</>
);
```
- 알바토크 전용 게시글 정렬 드롭다운
- 쿠키관리로직 서버컴포넌트 이동
> Feat: 알바폼 생성 시 단계별 드롭다운 추가

- public/icon/info-lg.svg
- public/icon/info-md.svg
- src/components/toast/ToastItem.tsx
- src/types/toast.ts
- 기본 유형 info, success, warning으로 변경했습니다.
- 유형별 아이콘 수정했습니다.
> Style: Toast 기본 유형 변경 및 유형별 아이콘 수정

- src/app/addform/components/StepButton.tsx
- src/app/addform/components/Title.tsx
- src/app/addform/layout.tsx
- src/app/addform/page.tsx
- src/atoms/addFormAtom.ts
- src/components/dropdown/AlbaformCreateDropdown.tsx
- 알바폼 만들기 페이지의 타이틀에 있는 작성취소 버튼을 추가했습니다.
- 경고창에서 "예"를 누르면 사장님용 알바목록으로 갈 수 있습니다.
- 알바폼 만들기 1단계
- 스키마 분기처리 및 검증로직
- 만들어둔 드롭다운까지 포함했습니다.
- PC에서는 버튼식, 태블릿부터는 드롭다운이라 화면이 반응형에서 전환이 되더라도 단계가 따로따로 진행되지 않도록 했습니다.
- URL 파라미터 키 이름을 step으로 일원화했습니다.
> Feat: 알바폼 만들기 페이지 작성취소 버튼 추가

- src/app/addform/components/StepButton.tsx
- src/app/addform/components/StepContainer.tsx
- src/app/addform/components/StepOneContents.tsx
- src/app/addform/components/StepThreeContents.tsx
- src/app/addform/components/StepTwoContents.tsx
- src/app/addform/components/Title.tsx
- src/app/addform/layout.tsx
- src/app/addform/page.tsx
- src/atoms/addFormAtom.ts
- src/components/dropdown/AlbaformCreateDropdown.tsx
- src/schema/addForm/addFormSchema.ts
- 알바폼 만들기 페이지에서 사용할 서버전달용 zod 스키마를 추가했습니다.
- 검증로직도 포함한 상태입니다.
- 단계별 form을 만들고 해당 단계에 맞는 register와 errors를 가져와 입력받을 수 있도록 세팅해놨습니다.
- 다른 팀원님이 오시면 form 만들고 세팅해둔 register와 errors를 가지고 각 input 요소에 적용해주시면 됩니다.
- 1단계 form 작업
- form을 만들며 알바폼 만들기 페이지가 진행되면서 일부 zod 스키마와 정규식이 변경될 수 있습니다.
- imageUrls는 별도 이미지 업로드 관련 로직을 만들어야 해서 스키마에 넣지 않았습니다.
- 이미지 관련 로직 작업 후 zod 스키마에 imageUrls 넣을 것으로 예상은 되는데, 작업하면서 고려해보겠습니다.
> Feat: 알바폼 만들기 페이지 zod 스키마 검증 및 단계별 분기처리 세팅

- src/schema/apply/applySchema.ts
applySchema 수정하였습니다.
1. password : 4자 이상 12자 이하
2.  experienceMonths (경력) : 숫자(정수) 만 가능, 600개월까지 가능
3. resumeName(이력서) : 허용 파일 pdf, word 만 가능
지원하기 폼 기능 구현
1. 이력서 제출 기능
2. 폼 제출 기능
패스워드 유효성 검사 에러 메세지를 수정하여 "*지원내역 확인에 사용됩니다." 라는 문구와 겹치지 않게 하였습니다.
> Chore: 지원하기 폼 벨리데이션 수정

- src/components/card/PostCard.tsx
리스트되는 PostCard를 수정하였습니다.
1. 각 카드가 상세페이지로 이동 되도록 Link 컴포넌트 사용
2. 각 카드에 쉐도우 넣었습니다.
3. 각 카드에 드랍다운이 알바토크 페이지에서는 안보이도록 하였습니다. (마이페이지에서는 보여야함)
추후 마이페이지에서 케밥버튼을 드랍다운으로 적용 시켜야합니다. (현재 버튼으로 되어있음)
> Chore:PostCard Link이동/ shadow /드랍다운 여부 수정

- src/app/alba/[formId]/components/ApllicantActionButtons.tsx
- src/app/alba/[formId]/page.tsx
- 알바폼 상세페이지에서 지원자인 경우 ApllicantActionButtons 버튼을 렌더링하게 했습니다.
- ApllicantActionButtons는 formId를 받아 지원하기 버튼을 눌렀을 떄에는 지원하기 페이지로 이동하고, 내 지원 내역 보기 버튼을 눌렀을 떄에는 이에 해당하는 모달을 띄웁니다.
https://github.com/user-attachments/assets/8d866ebb-38e7-4c86-9dc7-0586bf093400
https://github.com/user-attachments/assets/7db13384-ed6e-4fa9-bab7-3693ea01d70d
https://github.com/user-attachments/assets/fb6e95f5-b61e-42dc-855c-92f4a6580b42
내 지원 내역 보기 모달에서 입력값을 다 넣고 제출했을 때 어떤 UI를 보여줘야 할지 의논이 필요해 보입니다.
> Feat:  알바폼상세페이지 내 지원 내역 보기/지원하기 버튼 기능 활성화

- src/utils/isPast.ts
- 모집마감이 아닌데 모집마감 toast가 뜨는 버그 해결했습니다.
- 이유는 isPast 유틸함수의 return문 부등호가 반대로 되어있었습니다.
> Fix: isPast 유틸함수 return문 수정

- src/app/mypage/components/InfoEditContainer.tsx
- src/app/mypage/components/MyComment.tsx
- src/app/mypage/components/MyPost.tsx
- src/app/mypage/components/MyScrap.tsx
- src/app/mypage/components/NavMenu.tsx
- src/app/mypage/components/NavMenuButton.tsx
- src/app/mypage/layout.tsx
- src/app/mypage/page.tsx
1. 마이페이지 레이아웃을 잡아 놓았습니다.
- 타이틀
- 개인 정보 수정 버튼 or 케밥
- NavMenu ("내가 쓴 글", "내가 쓴 댓글", "스크랩")
- orderByDropdown 
- page content (메뉴에 선택 된 데이터가 랜더링 될 공간)
https://github.com/user-attachments/assets/7c54d0d4-f816-4e47-89cd-dfd84c6717dd
1. "내가 쓴 글", "내가 쓴 댓글", "스크랩" 을 각각 데이터 패칭하여 랜더링 해야합니다
2. 각 리스트에 무한스크롤 적용
3. 사장님의 경우 스크랩을 메뉴에서 제거
> Feat:마이페이지 레이아웃 구현

- src/app/(auth)/components/EazyLogin.tsx
- src/app/(auth)/signin/[userType]/page.tsx
- src/app/(auth)/signup/[userType]/page.tsx
- 로그인 및 회원가입 페이지에서 EazyLogin 컴포넌트가 보이도록 했습니다.
- 기능은 작업중인데 오래 걸릴 것 같아 ui만 push한  상황입니다.
https://github.com/user-attachments/assets/c51d325f-3722-472f-85f1-45ffb0c5b965
- 간편 로그인/회원가입 기능 구현
- 일단 작업중이긴 한데 Oauth를 처음 다뤄봐서 개념을 이해하고 적용하는데 시간이 조금 걸리는 것 같습니다(17일 자정 이후에나 구현 가능할 것으로 예상)
- 리팩토링 기간에 다른 분들 리팩토링 하실 때 저는 이거 매달려야 하나 흠.. 고민입니다
> Feat: SNS 간편로그인 UI만 구현

- src/app/test/page.tsx
- src/atoms/modalAtom.tsx
- src/atoms/modalAtomStore.ts
- src/components/modal/modalActions/selectProgressAction.ts
- src/components/modal/modalContent/DeleteAlbaformModal.tsx
- src/components/modal/modalContent/SelectProgressModal.tsx
- src/components/modal/modalManager/ModalManager.tsx
- src/hooks/useModal.ts
1. "지원상태" 선택 후 데이터 패칭 요청 기능 추가
2. 지원서 id를 받기 위해 전역 상태관리 추가하였습니다.
` export const applicationIdAtom = atom<number | null>(null);`
모달을 사용할 때 지원서 id값을 받아야하는데 전역으로 설정한 applicationIdAtom에 저장해줘야 합니다.
> Feat: "지원상태 수정" 모달 기능 구현

- src/components/button/LoginButton.tsx
- src/components/header/Header.tsx
- src/components/header/HeaderNavigation.tsx
- Header에 로그인이 되었냐 안되었냐는 로컬 스토리지에 isLogin이라는 키 값이 있다고 가정하고 구현했습니다. 로그인햇을 떄 로컬스토리지에 isLogin이 true | false로 들어갔으면 하는 바람입니다. 하하!
- 모바일일 떄 네비게이션이 줄바꿈이 생기는 문제는 아직 테스트는 안해봤는데 gap을 늘려서 됬을거라고 생각합니다. 배포했을때 생기는 문제라 2차 배포테스트 때 확인가능한 부분인 것 같습니다bun run dev로는 이전에도 괜찮게 보였음)
> Fix: Header컴포넌트 디버깅

- src/lib/instance.ts
- src/middleware.ts
- 기존에 instance를 통해 토큰이 포함된 요청을 했을 때 401 에러가 반환되면 리프레시토큰 요청 및 재요청 로직이 작동하지 않았습니다.
- 이 문제는 instance 함수에서 401에러 객체를 return하여 이후 로직이 실행되지 않았기 때문입니다. 즉, 이후 요청이 가로채지고 끝나버려서 발생한 문제였습니다.
- 그래서 instance 상단에서 미리 액세스토큰이 있나없나로 401에러를 반환하지 않고, 실제 요청을 한 이후에 관련 처리를 하도록 변경했습니다.
- 미들웨어도 전용페이지 접근을 차단하는 로직을 업데이트했습니다.
- 반환되는 데이터를 받으면 response.data.data 식으로 되는 것을 막기위해 해당 부분을 수정했습니다.
https://github.com/user-attachments/assets/184514a5-ada5-4088-951e-f7465fce46f2
- 이번 이슈에서는 없음
- 반환되는 데이터 객체를 수정했기 때문에 일부 컴포넌트에서 response.data 형식으로 수정이 필요할 수 있습니다. merge 되면 작업하신 부분의 요청이 잘 되는지 확인이 필요할 것 같습니다.
> Fix: instance 버그 수정 및 미들웨어 최신화

- src/app/addform/components/StepButton.tsx
- src/app/addform/components/StepContainer.tsx
- src/app/addform/components/StepOneContents.tsx
- src/app/addform/components/StepThreeContents.tsx
- src/app/addform/components/StepTwoContents.tsx
- src/app/addform/components/Title.tsx
- src/app/addtalk/components/AddTalkForm.tsx
- src/atoms/addFormAtomStore.ts
- 알바폼 만들기 PC화면의 '작성중' 태그를 값을 감지하여 값이 있을 때 뜨도록 했습니다.
- 수정하기를 통해 form이 나오면 모든 값이 있어야하는 상황이기에 세 단계에 모두 뜨도록 했습니다.
https://github.com/user-attachments/assets/1e474734-4a6d-4c53-a283-f06f9d896876
- 에러위치 수정
- 이 로직 수정으로 addform 컴포넌트의 코드가 많이 길어졌습니다.
- 리팩토링의 필요성이 갈수록 커져서 리팩토링을 진행 후 에러위치를 수정하는 작업을 해보겠습니다.
> Chore: 알바폼 만들기 작성중 태그 활성화 여부 로직 수정

- src/app/alba/[formId]/components/Content.tsx
- src/app/alba/[formId]/components/DetailRequirements.tsx
- src/app/alba/[formId]/components/SimpleRequirements.tsx
- src/utils/isPast.ts
- 1차 배포 때 알바폼 상세페이지에서 발견한 버그들 고치는 작업입니다. 리스트는 아래와 같습니다
> Fix: 알바폼상세페이지 디버깅 작업(80%완료)

- src/app/albatalk/components/AlbatalkList.tsx
- src/app/albatalk/layout.tsx
비회원일때 알바토크 페이지에 위치한 글쓰기 버튼을 안보이도록 했습니다.
로컬 스토러지의 isLogin을 활용하여 값이 있을 때만 보이도록 했습니다.
*플로팅 버튼의 위치를 레이아웃에서 클라이언트 랜더링쪽으로 옮겼습니다.
```
{isLogin && (
<div className="fixed bottom-20 right-10">
<FloatingButton icon="/icon/writing.svg" href="/addtalk" />
</div>
)}
```
https://github.com/user-attachments/assets/1a16392a-52e8-45c6-b277-87d205b5ac08
> Chore:글쓰기 버튼 비회원 숨기기

- src/app/addform/components/stepOne/AddformImage.tsx
- src/app/addtalk/actions/addTalk.ts
- src/app/addtalk/actions/patchPost.ts
- src/app/addtalk/actions/uploadImage.ts
- src/app/addtalk/components/AddTalkForm.tsx
- src/app/albatalks/[talkId]/actions/postComment.ts
- src/app/albatalks/[talkId]/getComments.ts
- src/components/button/ImageInput.tsx
- instance 업데이트로 인한 데이터의 return값 변경으로 기존의 response.data -> response로 return문 수정.
- 글쓰기 및 수정 시 요청 실패 토스트를 띄우며 페이지 이동하지 않는 에러.
- 댓글 목록 조회 에러.
- ImageInput **sizeCheck** prop 추가, 기본값은 false이며 true일 때 1560 x 560의 이미지 사이즈 검증하도록 수정. 
```
// 예시입니다.
<ImageInput
limit={3}
sizeCheck={true}
onImageChange={setCurrentImageList}
initialImage={currentImageList}
/>
```
> Fix: 알바 토크 글쓰기 및 상세 페이지 수정

- src/app/alba/[formId]/page.tsx
- src/components/ApplicantStatsList.tsx
- 사장님 전용 "지원 현황 조회" 모달에서 지원자 누를 경우 지원자 상세 페이지로 이동시키는 기능입니다.
https://github.com/user-attachments/assets/ba84e4d4-7e8c-4e27-a65f-7eaa2a0aff0d
- 사장님 전용 "지원자 상세 페이지" 만들어야 합니다.
- 사장님 전용이지만 페이지 ui는 "내 지원 상세 페이지"와 같기에 추측컨데 기존에 만들어 둔 페이지 컴포넌트를 재활용할 수 있어야 할 것 같습니다..
- 지원자 전용 "내 지원 상세 페이지"와 사장님 전용 "지원자 상세 패이지"의 ui가 같은데 url은 서로 다릅니다.(/myapply/{formId}) <-> (/application/{applicationId}) 
- ui는 같지만 url이 서로 다를때 어떻게 해야 효율적으로 컴포넌트를 렌더링 할 수 있을지가 키포인트인 것 같습니다!
> Feat: 지원현황조회 모달 -> 각 지원자 클릭시 "지원자 상세 페이지"로 이동하는 기능

- src/app/alba/[formId]/fetchAlbaformData.ts
- src/app/alba/[formId]/page.tsx
- src/components/Carousel/Carousel.tsx
- src/components/header/Header.tsx
- src/components/header/Logo.tsx
- 페이지 컴포넌트에서 데이터 패칭할때 5분동안 캐싱되도록 수정했습니다.
- 헤더에 로고와 페이지에 캐러셀 같은 경우 핵심적인 시각적 요소라고 판단하여 next/Image의 기본 값인 lazy loading이 아닌 loading="eager" 또는 priority를 명시해주었습니다
> 페이지가 로드되자마자 보이는 컨텐츠라면 어차피 바로 감지되었다고 인식하기 떄문에 그 차이가 미비하지만 lazy-loading은 브라우저에 감지되었는가를 확인할 때 observer api를 호출하기 때문에 그 부분에서 미세한 차이가 있을 수 있다고 이야기합니다! 맹신할 수 없는 지표이지만 실제로 넣고 안 넣었을 떄 lighthouse에서 80대에서 90대까지 올라가는 모습이었습니다!
> Refactor: 알바폼 상세페이지

- src/app/alba/[formId]/page.tsx
- src/app/alba/components/ApllicantActionButtons.tsx
- 알바폼상세페이지에서 자기 폼이 아닐 때 ActionButtons가 렌더링 되지 않게 할려고 isMyAlbaform이라는 사장님 전용 변수를 만들어놨는데 이것이 지원자 전용일 떄에도 영향을 줘서 서로 영향을 주지 않게 분기처리 했습니다.
- 지원자가 로그인하고 알바폼 상세페이지로 들어가 "내 지원 내역 보기" 버튼을 눌렀을 때 기존에는 모달이 떴는데 이번에는 바로 /myapply/{formId}로 보내게 했습니다. 로컬 스토리지에 isLogin이 있는지 없는지로 구분했습니다.
> Fix: 알바폼상세페이지에서 지원자일 때 ActionButton이 이상하게 배치되는 문제 해결

- src/components/PostCardThumbnail.tsx
- src/components/card/PostCard.tsx
알바토크페이지의 게시글에 썸네일을 추가했습니다.
제목과 본문이 길어질 때 '...' 으로 축약되도록 수정하였습니다.
> Feat:PostCard 썸네일 추가

- src/components/modal/modalActions/selectProgressAction.ts
- src/components/modal/modalContent/SelectProgressModal.tsx
진행 상태 변경 모달 로직을 수정하였습니다.
1. 데이터 패칭에 오류가 발생하였는데 보내주는 body값이 {status: body} 이렇게 보내줘야 했는데 body만 보내서 문제가 생겼었습니다.
2. 기존에는 applicationId를 전역상태로 관리하였는데 현재는 페이지에서 받아올수 있기 때문에
모달 내에서 useParams를 사용하여 applicationId를 받아올 수 있도록 변경하였습니다.
https://github.com/user-attachments/assets/d294da19-d296-4bda-ac45-491845f6935e
모달로 진행상태를 변경하였을 때 페이지에서 즉각적으로 상태를 반영하기 위해
window.location.reload(); 코드 사용
> Fix:진행상태 변경 모달 로직 수정

- src/app/layout.tsx
- src/lib/RedirectWarning.tsx
- src/middleware.ts
- 비회원이 접근할 수 없는 페이지에 접근할 수 있었던 현상을 수정했습니다.
- 리다이렉트 되면 토스트가 띄워지도록 했습니다.
https://github.com/user-attachments/assets/7fd734e7-bdc3-4831-bdab-587ae8980251
- 없음
- 기존에 ownerPath.includes(path) 이런식으로 설정해놨었는데, 이는 path에 해당되는 정확한 URL일 때만 해당된다고 합니다.
- 그래서 path.startsWith로 ownerPath와 applicantPath에 속하는 URL로 들어가면 로그인페이지로 이동하도록 했습니다.
- 비회원일 떄 뜨는 토스트내용, 회원인데 전용페이지로 들어갔을 경우의 토스트내용이 서로 다르게 했습니다.
> Chore: 비회원이 접근할 수 없는 페이지 접근되는 현상 수정

- src/app/addform/[id]/page.tsx
- src/app/addform/components/MainButton.tsx
- src/app/addform/components/StepContainer.tsx
- src/app/addform/components/StepContent.tsx
- src/app/addform/components/StepOneContents.tsx
- src/app/addform/components/StepThreeContents.tsx
- src/app/addform/components/StepTwoContents.tsx
- src/app/alba/[formId]/components/OwnerActionButtons.tsx
- src/app/alba/[formId]/fetchAlbarformDetailData.ts
- 임시저장 데이터가 로컬스토리지에 있더라도 수정하기 페이지로 들어가면 불러오지 않도록 수정했습니다.
- 알바폼을 수정하면 상세페이지에서 바로 반영되도록 수정했습니다.
- 알바폼을 수정하면 수정하기페이지에서 바로 반영되도록 수정했습니다.
https://github.com/user-attachments/assets/7297186d-cf3f-4bb8-8660-355a4f4cf7bf
https://github.com/user-attachments/assets/7170eeeb-fb2c-4643-9621-71fe57b0cec2
- 없음
- 알바폼 수정 후 알바폼 상세페이지에 반영되기까지 시간이 걸립니다.
- 알바폼 상세페이지가 캐싱된 상태여서 revalidate로 정한 시간이 되서야 새로 업데이트되는 문제였습니다.
- 그래서 revalidate에 tag를 설정하여 수정되면 즉시 반영되도록 했습니다.
- 수정하기페이지에서 업데이트되지 않는 부분 역시 tag를 사용하여 수정했습니다.
> Chore: 알바폼 수정하기로 들어갔을 때 임시저장데이터 불러오지 않도록 수정

- src/app/addform/components/StepContainer.tsx
- src/app/addform/components/StepOneContents.tsx
- src/app/addform/components/StepTwoContents.tsx
- src/hooks/useAddFormStepOne.ts
- 알바폼 수정하기페이지를 들어가면 딜레이가 생기는데 이를 약간 완화했습니다.
- 완전히 제거하지는 못했습니다.
https://github.com/user-attachments/assets/52cfa22d-a013-45df-90fe-820225d4fd24
- 없음
- 최적화 훅의 적절한 사용을 했는데도 완전 제거가 안되서 react-hook-form의 watch를 구독하는 부분이 늘어나면서 생긴건지 원인을 파악하는 중에 있습니다.
- 알바폼 만들기페이지와 내용의 유무만 차이날 뿐 다른 부분이 없는데 만들기페이지는 딜레이가 없어서 외부적인 요인 때문인지도 확인해봐야 할 것 같습니다.
> Chore: 알바폼 수정하기 페이지 딜레이현상 완화

- src/lib/instance.ts
- src/middleware.ts
- 새 액세스토큰 발급 후 재요청로직만 instance로 옮겼습니다.
- 이제 새 액세스토큰이 저장되면 문제없이 기존요청을 이어갈 수 있습니다.
https://github.com/user-attachments/assets/809ebc63-ca8e-4203-b373-968c48f82c97
- 없음
- 기존에는 새 액세스토큰을 발급받아도 이후 기존요청이 처리가 안되는 현상이 있었습니다.
- 영상에서는 get요청을 테스트하여 새 액세스토큰을 받아오면 기존 get 요청이 이어지는 것을 확인하실 수 있습니다.
> Chore: 재요청로직만 instance로 복귀

- src/components/button/ImageInput.tsx
- 최종배포 이후 생긴 이미지 무한루프 현상을 수정했습니다.
https://github.com/user-attachments/assets/cc879356-d1ca-482f-a427-3216db286dbc
- 없음
- ImageInput의 원인 코드를 수정했습니다.
- 첫 useEffect에서 의존성배열에 selectedImages가 포함된 게 원인이었는데, 생략하면 eslint 경고가 떠서 아래와 같은 코드를 추가했습니다.
```
const selectedImagesRef = useRef(selectedImages);
selectedImagesRef.current = selectedImages;
useEffect(() => {
if (initialImage?.length) {
selectedImagesRef.current.forEach((url) => URL.revokeObjectURL(url));
const newImages = initialImage.map((img) => URL.createObjectURL(img));
setSelectedImages(newImages);
setNewFiles(initialImage);
}
}, [initialImage]);
```
> Chore: 알바폼만들기 및 수정하기 이미지 무한루프 수정
