- src/components/RoundedButton.tsx
- tailwind.config.ts
- [albaform #23 ]
<br/>
- size의 기본값은 small입니다.
- rest prop을 사용하여 button에 속성을 추가할 수 있습니다.
- props의 타입입니다.
``` 
children: string;
size?: "small" | "large";
[key: string]: any;
> Feat(23): RoundedButton 구현

- src/components/CancelButton.tsx
- tailwind.config.ts
- [alboform #24 ]
<br/>
- size의 기본값은 small입니다.
- rest prop을 사용하여 button에 속성을 추가할 수 있습니다.
- props의 타입입니다.
```
children: string;
size?: "small" | "large";
[key: string]: any;
> Feat(24): CancelButton 구현

- src/components/button/FloatingButton.tsx
- tailwind.config.ts
- [albaform #26 ]
<br/>
- icon은 필수이며, children을 통해 버튼에 텍스트를 적용할 수 있습니다.
- color에 따라 스타일이 다르게 적용됩니다.
- rest prop을 통해 버튼의 속성을 변경할 수 있습니다.
- position 속성을 사용해 버튼의 위치를 조정할 수 있습니다.
- 컴포넌트의 prop 타입입니다.
```
icon: string;
size?: "small" | "large";
color?: "orange300" | "oldLace50" | "white";
children?: string;
className?: string;
[key: string]: any;
> Feat: FloatingButton 구현

- src/components/button/RadioButton.tsx
- [albafomr #27 ]
<br/>
- checked, disabled 상태에 따라 스타일이 변경됩니다.
- RadioButton의 prop 타입입니다.
```
name: string;
value: string;
checked?: boolean;
disabled?: boolean;
onChange?: (value: string) => void;
checked, default, disabled 순입니다.
> Feature: RadioButton 구현

- src/app/globals.css
- src/app/modaltest/page.tsx
- src/components/modal/modalContent/DeleteAlbaformModal.tsx
- src/components/modal/modalContent/PatchAlbaformModal.tsx
- src/components/modal/modalContent/SelectProgressModal.tsx
- src/components/modal/modalManager/ModalManager.tsx
- src/types/modal.tsx
- tailwind.config.ts
- 제목 : feat(issue 번호): 기능명
ex) feat(17): pull request template 작성
(확인 후 지워주세요)
- [ #36 ]
<br/>
- "진행 상태 모달" UI 구현했습니다.  (SelectProgressModal)
<br/>
<br/>
- 추후 선택한 상태를 내보내는 기능 구현이 필요합니다.
<br/>
1. radio 사용법 : name 속성 활용하여 하나만 선택하게 하기
2. radio 커스텀 : appearance-none 하고 새로 만들기 / ring, border, bg 활용
> feat: "진행상태 선택" 모달 UI 구현

- src/components/button/CheckBoxButton.tsx
- [albaform #28 ]
<br/>
- size, checked, disabled에 따라 스타일이 다르게 적용됩니다.
- size의 기본값은 "small", checked와 disabled의 기본값은 false입니다.
- 사용 예시입니다.
``` 
const Page = () => {
const [checked, setChecked] = useState(false);
const handleCheckBoxToggle = () => {
setChecked((prev) => !prev);
};
return (
<div>
<CheckBoxButton
name="버튼 이름"
value="값"
checked={checked}
onChange={handleCheckBoxToggle}
/>
<div>
}
> Feat: CheckBoxButton 구현

- src/components/dropdown/ApplicationDropdown.tsx
- 앞서 merge 했던 모집현황별 드롭다운의 코드를 dropdownMenu 최신화에 따라 스타일부분만 수정했습니다.
- 알바폼 생성에서의 드롭다운
- 게시글 정렬 드롭다운
> Style: dropdownMenu 최신화에 따라 적용할 스타일코드 수정

- src/schema/signin/signinSchema.ts
- src/schema/signup/signupSchema.ts
- 비밀번호 스키마에 최대길이 (12자 이내) 설정, 모든 특수기호를 커버할 수 있도록 수정했습니다.
- 에러메세지도 일부 수정했습니다.
|                            12자 이내 에러메세지 표출                    |                       수정한 정규식 에러메세지                        |
| :--------------------------------------------------------------------: | :-------------------------------------------------------------------:  |
|   <img src="https://github.com/user-attachments/assets/6c14939e-e163-43fb-80ff-c9a491885f7c" fill>     | <img src="https://github.com/user-attachments/assets/bdb32ddc-44be-4faf-9e92-f2e930a3013b" fill>     |       
- 드롭다운 UI 추가 작업
> Chore: 회원가입 및 로그인 비밀번호 스키마 수정

- src/atoms/dropdownAtomStore.ts
- src/components/dropdown/DropdownMenu.tsx
- src/components/dropdown/EditDeleteDropdown.tsx
- src/components/dropdown/OrderByDropdown.tsx
- src/components/dropdown/PublicDropdown.tsx
- src/components/dropdown/RecruitDropdown.tsx
- 최신순, 시급 높은 순, 지원자 많은 순, 스크랩 많은 순으로 정렬할 수 있는 드롭다운입니다.
- 알바폼 목록 조회 api에서 서버에 orderBy 값으로 보낼 수 있습니다.
- 기본값은 최신순으로 설정되어 있습니다.
- 다음 코드처럼 사용이 가능합니다.
```
const orderBy = useAtomValue(orderByAtom);
console.log(orderBy.value, orderBy.title);
return <OrderByDropdown />
```
- 알바폼 생성 드롭다운
- 내 정보 수정, 비밀번호 변경 드롭다운
- 이미 merge된 드롭다운들의 수정사항도 포함되어 있습니다.
> Feat: 게시글 정렬 드롭다운 추가

- src/components/button/SolidButton.tsx
- SolidButton **gray100** style 추가하였습니다.
> Chore: SolidButton style 추가

- src/components/toast/ToastContainer.tsx
- src/components/toast/ToastItem.tsx
Toast 여러 개 생성 시 아래에서 위로 쌓이도록 순서 변경.
> Style: Toast 생성 순서 변경

- src/app/(auth)/signin/actions/signinActions.ts
- src/app/(auth)/signin/components/SigninContents.tsx
- src/app/(auth)/signup/actions/signupActions.ts
- src/app/(auth)/signup/components/SignupContents.tsx
- src/schema/signup/signupSchema.ts
- 회원가입 및 로그인에 토스트를 적용합니다.
- 회원가입과 로그인 시 서버로부터 반환되는 에러메세지가 현재 영문이어서 한글화합니다.
- 쿠키관리 서버컴포넌트로 이동작업
- Chore 이슈 탬플릿이 초기화된 것 같아서 확인이 필요할 것 같습니다.
> Chore: 회원가입 및 로그인 토스트 적용 및 에러메세지 한글화

- src/app/alba/[formId]/layout.tsx
- src/app/alba/[formId]/page.tsx
- 레이아웃 짠다고 했는데 별게 없어서 작업 코드가 많지 않습니다.
- 캐러셀 컴포넌트는 아직 미구현이라 여기 배치될 것이다~하고  주석처리만 해놨습니다.
- 캐러셀 구현 
- 각 섹션에 들어갈 컴포넌트 구현
> Feat: 알바폼 상세 페이지 layout 작업

- src/components/card/DetailRequirements.tsx
> Style : tailwind 수정

- src/app/test/page.tsx
- src/components/card/EmployerInfo.tsx
- tailwind 조금 수정하고 모바일 ui 추가했습니다.
> Style: tailwind 수정, 모바일 반응형 구현

- src/components/button/SolidButton.tsx
- 기존의 size prop을 받는 방식에서 size prop을 받지 않고 반응형으로 작동하도록 로직 수정. 
준영님의 요청으로 작동 방식을 변경하였습니다. 확인 부탁드립니다.
> Refactor: SolidButton 로직 수정

- src/app/addform/components/MainButton.tsx
- src/app/addform/components/StepButton.tsx
- src/app/addform/components/StepContainer.tsx
- src/app/addform/components/StepOneContents.tsx
- src/app/addform/components/StepSidebar.tsx
- src/app/addform/components/StepThreeContents.tsx
- src/app/addform/components/StepTwoContents.tsx
- src/app/addform/components/Title.tsx
- src/app/addform/layout.tsx
- src/app/addform/page.tsx
- src/atoms/addFormAtom.ts
- src/components/dropdown/AlbaformCreateDropdown.tsx
- src/schema/addForm/addFormSchema.ts
- PC화면에서만 나오던 두 버튼을 태블릿과 모바일에서도 보이도록 했습니다.
- 1단계 form 작업
- 이전 PR까지 포함되어 있어서 파일 수가 늘어나보이고 있습니다. 앞선 PR merge 후 차례대로 merge 하겠습니다.
> Chore: 임시저장 및 등록하기 버튼 별도 컴포넌트화하여 반응형 구현

- src/app/apply/[id]/components/ApplyForm.tsx
- src/app/apply/[id]/layout.tsx
- src/app/apply/[id]/page.tsx
- src/schema/apply/applySchema.ts
1. 알바폼 지원하기 UI 구현 (페이지, 레이아웃, 지원하기 폼 )
https://github.com/user-attachments/assets/65e68044-24cc-434c-a672-35c1e54f5af6
1. 폼 벨리데이션 필요 (이력서, 경력 부분)
2. 이력서 인풋 기능 구현 필요
3. 폼 제출 기능 구현 필요
"작성 취소" 버튼을 공통 버튼 중 SolidButton 사용하였는데 사이즈를 div로 감싸서 줄여도 원하는 만큼 줄어들지 않습니다.
> Feat:알바폼 지원하기 UI 구현

- src/app/addform/components/MainButton.tsx
- src/app/addform/components/StepContainer.tsx
- src/app/addform/components/StepOneContents.tsx
- src/app/addform/components/StepSidebar.tsx
- src/app/addform/components/StepThreeContents.tsx
- src/app/addform/components/StepTwoContents.tsx
- src/app/addform/components/Title.tsx
- src/app/addform/page.tsx
- src/app/test/page.tsx
- src/atoms/addFormAtom.ts
- src/components/button/ImageInput.tsx
- src/components/picker/Calendar.tsx
- src/components/picker/DatepickerCalendar.tsx
- src/components/picker/RangePicker.tsx
- src/schema/addForm/addFormSchema.ts
- src/styles/globals.css
- 1단계 form을 구현했습니다.
- 임시저장된 데이터가 있으면 불러와서 해당 값이 채워지도록 했습니다.
- 이미지는 blob 주소가 원인인지 다른 부분이 문제인지 불러오면 화면에 표출되지 않아서 일단 제외했습니다.
https://github.com/user-attachments/assets/984775a9-82ef-44df-a2aa-ade09c309b5f
- 2단계 form 작업
- 3단계 form 작업 및 서버액션 추가
- 작업하면서 임시저장 이미지 표출하는 방법 연구
- 준영님 파일에 type=button 외 추가한 코드가 있습니다.
- 시작일과 종료일 데이터를 추출해서 임시저장과 react-hook-form의 value에 등록해야하기에 추가했습니다.
- 이 부분은 내일 함께 더 이야기해보면 좋을 것 같습니다.
> Feat: 알바폼만들기 페이지 1단계 form 생성, 임시저장 불러오기 추가

- src/components/modal/modalContent/ClosedAlbaformModal.tsx
> Chore:Close모달 홈으로가기 -> 뒤로가기 변경

- src/app/alba/[formId]/page.tsx
- src/app/apply/[id]/components/ApplyForm.tsx
- src/components/modal/modalActions/deleteAlbaformAction.ts
- src/components/modal/modalContainer/ModalContainer.tsx
- src/components/modal/modalContent/DeleteAlbaformModal.tsx
1. 모달 모바일 일 때 w-full 적용
2. 삭제하기 모달 버튼 텍스트 수정
3. 삭제하기 기능 구현
https://github.com/user-attachments/assets/6858a3b7-3d06-42f2-be44-84ed907bfe88
> Chore: 삭제하기 모달 수정

- src/app/test/page.tsx
- src/components/modal/modalActions/changeMyInfoAction.ts
- src/components/modal/modalContent/ChangeMyInfoModal.tsx
- src/schema/modal/changeMyInfoSchema.ts
1. "나의 정보 수정" 모달 입력폼 입력 후 PATCH 요청 구현하였습니다
https://github.com/user-attachments/assets/997a53b0-ea3c-4d3e-8f44-6184f13a51b3
signup 컴포넌트의 profileImg, action 을 사용했습니다.
> Feat: "나의 정보 수정" 모달 기능 구현

- src/app/page.tsx
- src/components/button/LandingButton.tsx
- FCP 최적화 위해 정적페이지로 만듦
- 랜딩페이지에서만 쓰는 LandingButton 구현
- 랜딩페이지만 pb-32 줌
https://github.com/user-attachments/assets/38ba4713-519c-4b46-8281-a100141fadf0
> Refactor: 랜딩페이지 리팩토링

- src/components/dropdown/ApplicationDropdown.tsx
- src/components/dropdown/DropdownMenu.tsx
- src/components/dropdown/OrderByDropdown.tsx
- src/components/dropdown/PublicDropdown.tsx
- src/components/dropdown/RecruitDropdown.tsx
- 드롭다운에서 mb-1을 삭제하고, mb-1이 필요한 각 드롭다운에서 추가해줬습니다.
- 드롭다운 텍스트와 배경색이 잘못 적용된 부분을 수정했습니다.
https://github.com/user-attachments/assets/596d31d0-4986-417f-a934-6170f9603d6c
- 이 이슈에서는 없음
> Chore: 드롭다운 mb-1 삭제 후 수정필요한 드롭다운에서 해당 부분 추가

- src/app/addform/[id]/page.tsx
- src/app/addform/actions/addFormImgUpload.ts
- src/app/addform/actions/addFormSubmit.ts
- src/app/addform/components/StepTwoContents.tsx
- src/components/picker/RequirementPicker.tsx
- src/utils/formatAddFormDate.ts
- 2단계 에러위치가 기존에는 한 곳에 뭉쳐서 나왔는데, 이를 각 영역의 아래에 표출되도록 수정했습니다.
- 수정된 instance 반환 형식에 맞춰서, get과 post 및 patch 요청데이터 받는 코드를 수정했습니다.
- 첨부할 영상이 없어서 알바폼이 잘 등록된 사진을 첨부합니다.
- 없음
- instance의 요청데이터 반환을 ...responseData로 해놔서, 상당수의 요청에서 수정이 필요할 것으로 보입니다.
> Chore: 알바폼만들기 2단계 에러위치 수정, 요청데이터 받는 코드 수정

- src/app/addform/components/stepOne/AddformImage.tsx
- src/app/addtalk/actions/addTalk.ts
- src/app/addtalk/actions/patchPost.ts
- src/app/addtalk/actions/uploadImage.ts
- src/app/addtalk/components/AddTalkForm.tsx
- src/app/albatalks/[talkId]/actions/postComment.ts
- src/app/albatalks/[talkId]/getComments.ts
- src/components/button/ImageInput.tsx
- src/utils/renameIfKorean.ts
- 한글명으로 된 이미지 파일을 서버에 업로드 후 받은 url 값 사용 시 에러 발생.
- ImageInput을 통한 이미지 선택 시 한글명으로 된 파일을 영어 파일명("image")으로 수정하는 로직 추가.
> Chore: Imageinput 이미지 선택 시 한글명 파일을 영어로 수정하는 로직 추가

- src/app/albatalks/[talkId]/components/EmptyComments.tsx
- src/app/mypage/actions/getRole.ts
- src/app/mypage/components/MyScrapList.tsx
- src/app/mypage/components/NavMenu.tsx
> Feat:사장님일때 스크랩 안보이기

- src/app/addform/actions/addFormSubmit.ts
- src/app/albalist/getAlbaList.ts
- src/app/albatalks/[talkId]/components/CommentItem.tsx
- src/app/albatalks/[talkId]/components/Content.tsx
- src/app/albatalks/[talkId]/getAlbaTalkDetail.ts
- src/app/albatalks/[talkId]/getComments.ts
- src/app/myalbaform/components/ListFetcher.tsx
- src/app/myalbaform/getAlbaFormList.ts
- src/app/myalbaform/getApplyList.ts
- src/app/myalbaform/page.tsx
- 알바 목록(AlbaList), 알바 토크 상세(AlbaTalks) no-store 적용.
- 내 알바폼(MyAlbaForm) revalidate 5분 및 (tags: ["myalbaform"]) 적용.
- 알바폼 생성 시 revalidateTag("myalbaform") 적용하여 내 알바폼 캐시 무효화 적용.
> Refactor: 캐싱 전략 수정

- src/app/(auth)/layout.tsx
- src/app/(auth)/signin/components/SigninContents.tsx
- src/app/(auth)/signup/components/SignupContents.tsx
- src/app/(auth)/signup/components/SignupSecondContents.tsx
- src/app/addform/components/MainButton.tsx
- 새로운 솔리드버튼 size 속성과 값에 따라 버튼을 수정했습니다.
https://github.com/user-attachments/assets/cde031a1-beff-4151-a3ce-f33a6d497148
- 없음
- 없음
> Chore: 새로운 solid 버튼 사이즈 속성에 맞게 수정

- src/app/addtalk/components/AddTalkForm.tsx
- src/app/alba/[formId]/components/ApllicantActionButtons.tsx
- src/app/alba/[formId]/page.tsx
- src/app/alba/components/ApllicantActionButtons.tsx
- src/app/alba/components/Title.tsx
- src/app/application/[formId]/[applicationId]/layout.tsx
- src/app/application/[formId]/[applicationId]/page.tsx
- src/app/myapply/[formId]/fetchApplicationData.ts
- src/app/myapply/[formId]/layoute.tsx
- src/app/myapply/[formId]/page.tsx
- src/app/page.tsx
- src/components/ApplicantStatsList.tsx
- src/components/button/LoginButton.tsx
- src/components/card/AlbarPreview.tsx
- src/components/header/AuthPageNavigation.tsx
- src/components/header/Header.tsx
- src/components/header/HeaderNavigation.tsx
- src/components/header/Logo.tsx
- src/components/header/Sidebar.tsx
- src/styles/globals.css
- 이슈에 적어두었습니다.
@venise5224  
ResumInput 안에서 pathname을 통해 분기처리를 하면 어떨까 싶습니다. 
지원하기 페이지이면 기존에 쓰시던대로 react-hook-form과 관련된 코드를 사용하시고
myapply 페이지이면 react-hook-form은 없되 똑같이 연필모양을 누르면 파일 업로드가 뜨면서 파일을 선택/수정 할 수 있게하고 
application 페이지이면 다운로드가 될 수 있게요!
@wooy0 @byeolee1221 @venise5224 
globalcss에 body에 margin-bottm:180px 적용했습니다 각 페이지에서 아래 여백 주던거는 다 없애주셔야 합니다!
> Fix: 3차배포 디버깅 정준영(80% -> ResumInput만 반영하면 됨)

- src/app/albatalk/components/PostCardSkeleton.tsx
- src/app/apply/[id]/actions/applyFormAction.ts
- src/app/apply/[id]/components/ApplyForm.tsx
- src/app/mypage/actions/getRole.ts
- src/app/mypage/components/NavContainer.tsx
- src/app/mypage/components/NavMenu.tsx
- src/app/mypage/layout.tsx
1.지원하기 데이터 패칭 문제
2.스켈레톤 UI 수정
3.사장님의 경우 스크랩 안보이기
> Chore:배포전 전체 작업 수정

- src/app/(auth)/signup/actions/OAuthActions.ts
- 간편로그인에서 남아있는 구글 관련 코드를 삭제했습니다.
- 없음
- 없음
- 제 계정으로는 이미 가입이 되어버려서 더 이상의 회원가입 테스트가 불가능합니다.
- 테스트 가능하신 분은 회원가입이 잘 되는지 한번 확인해주시면 감사하겠습니다.
- 회원가입 데이터는 모두 잘 받고 있고, 테스트 성공할 당시의 코드와 동일해서 간편회원가입이 안된다면 다른 부분을 체크해봐야 할 것 같습니다.
> Chore: 구글 관련 코드 삭제
